# Permalinks
permalink:        pretty

# Setup
title:            Unofficial Economist
tagline:          'Hannah Blackburn'
description:      'Testing'
url:              http://hannahblackburn.github.io/test_from_hyde
baseurl:          /

author:
  name:           'Hannah Blackburn'
  url:            https://twitter.com/hannah_h_b

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hannahblackburn/test_from_hyde
