# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Unofficial Economist
tagline:          'Hannah Blackburn'
description:      'Testing <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://hannahblackburn.github.io/unofficialeconomist
baseurl:          /

author:
  name:           'Hannah Blackburn'
  url:            https://twitter.com/hannah_h_b

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/hannahblackburn/test_from_hyde
